name: On Push, Fuzz

on: push

env:
  fuzz_dir: KubeSec-master

jobs:
  hello-world:
    name: Hello world
    runs-on: ubuntu-latest
    steps:
    - name: Run Fuzz
      run: python ${{ env.fuzz_dir }}/fuzz.py
      shell: sh
