name: On Push, Fuzz

on: push

jobs:
  fuzz:
    name: fuzz
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Run Fuzz
      run: python KubeSec-master/fuzz.py
      shell: sh
